### PR TITLE
Minor fixes for Numpy 2

### LINKED ISSUE #1225: Main build failing with 'RuntimeWarning: overflow encountered in scalar subtract'
Looks like it may be due to stricter checks in NumPy 2.0.0.

```
tau_p = np.uint8(0), lambda_p = np.float64(0.0), ploidy_p = np.uint64(2)
kinship_pp = 0.0, tau_q = np.uint8(2), lambda_q = np.float64(0.167)
ploidy_q = np.uint64(4), kinship_qq = np.float64(0.307798800184587)
kinship_pq = 0.0

    @numba_jit
    def _hamilton_kerr_inbreeding_non_founder(
        tau_p: int,
        lambda_p: float,
        ploidy_p: int,
        kinship_pp: float,
        tau_q: int,
        lambda_q: float,
        ploidy_q: int,
        kinship_qq: float,
        kinship_pq: float,
    ) -> float:  # pragma: no cover
        """Calculate the inbreeding coefficient of a non founder
        individual i with parents p and q.
        """
        pat = (
            tau_p
>           * (tau_p - 1)
            * (lambda_p + (1 - lambda_p) * ((ploidy_p * kinship_pp - 1) / (ploidy_p - 1)))
        )
E       RuntimeWarning: overflow encountered in scalar subtract
```

From https://github.com/sgkit-dev/sgkit/actions/runs/9540232291/job/26291678469

### PR DESCRIPTION
**Pull request by timothymillar**
Fixes #1225

This only fixes a couple of small issues for Numpy 2 compatibility. However, many tests are still failing due to Cython-Numpy 2 compatibility issues. See https://github.com/brentp/cyvcf2/issues/307.

### CODE REVIEW

**Comment by timothymillar** [comment]
Tests now failing with cyvcf2 code: `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Review by tomwhite — APPROVED** [review]
LGTM thanks @timothymillar

The cyvcf2 fix is not ready yet so should we merge this now, along with a numpy<2 pin?

**Comment by timothymillar** [comment]
cyvcf2 and cbgen both have new releases for numpy 2 (the latest cbgen pins to numpy >= 2). But the tests against scikit-allel are still failing. Maybe time to add the scikit-allel test data and drop the dependency?

**Review by tomwhite — APPROVED** [review]
Good to merge now

**Comment by jeromekelleher** [comment]
Agreed, let's pin to numpy < 2 for now and push out a release?

**Comment by tomwhite** [comment]
> But the tests against scikit-allel are still failing. Maybe time to add the scikit-allel test data and drop the dependency?

I wonder if we need the scikit-allel conversion still? We could deprecate [`read_scikit_allel_vcfzarr`](https://sgkit-dev.github.io/sgkit/latest/generated/sgkit.read_scikit_allel_vcfzarr.html#sgkit.read_scikit_allel_vcfzarr). The VCF reading code is going to be replaced by bio2zarr soon anyway.

Thoughts @jeromekelleher?

**Comment by jeromekelleher** [comment]
I'm wondering the same, it may be best to just drop direct VCF support soon and be done with it.

**Pull request merged**
